export const PRIMARY       = '#059669'
export const PRIMARY_DARK  = '#047857'
export const PRIMARY_LIGHT = '#ECFDF5'
export const PRIMARY_MID   = '#A7F3D0'
export const CANVAS        = '#FFFFFF'
export const BODY_BG       = '#F4F4F5'
export const INK           = '#18181B'
export const BODY          = '#52525B'
export const MUTED         = '#71717A'
export const HAIRLINE      = '#E5E7EB'
export const BORDER_STRONG = '#8F8F8F'
export const DANGER        = '#DC2626'
export const DANGER_BG     = '#FEF2F2'
export const DANGER_TEXT   = '#991B1B'
export const DANGER_BORDER = '#FECACA'
export const SUCCESS       = '#059669'
export const SUCCESS_TEXT  = '#047857'

export const FONT_HEADING = "'Inter Tight', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
export const FONT_BODY    = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
export const FONT_MONO    = "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace"
