export const PRIMARY       = '#4F46E5'
export const PRIMARY_DARK  = '#4338CA'
export const PRIMARY_LIGHT = '#EEF2FF'
export const PRIMARY_MID   = 'rgba(79, 70, 229, 0.35)'
export const CANVAS        = '#F8FAFC'
export const BODY_BG       = '#FFFFFF'
export const BONE          = '#F1F5F9'
export const INK           = '#0F172A'
export const BODY          = '#334155'
export const MUTED         = '#64748B'
export const HAIRLINE      = '#E2E8F0'
export const BORDER_STRONG = '#CBD5E1'
export const DANGER        = '#DC2626'
export const DANGER_BG     = '#FEF2F2'
export const DANGER_TEXT   = '#991B1B'
export const DANGER_BORDER = '#FECACA'
export const SUCCESS       = '#16A34A'
export const SUCCESS_TEXT  = '#15803D'

export const FONT_HEADING = "'Inter', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
export const FONT_BODY    = "'Inter', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
export const FONT_MONO    = "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace"
